jabardigitalservice/pikobar-pelaporan-backend

api/cases/route_prerequesites.js
api/cases/routes.js
api/histories/routes.js
api/users/route_prerequesites.js
services/cases.js

update permission role for endpoint case & history

---

models/History.js

perbaikan report_source kosong di database

set field report_source in History default value to null

---

helpers/casesheet/casesheet.js

di fitur import itu default province nya saya keliru, karena set defaultnya 35.  harusnya 32.
kenapa bisa saya set defaultnya "35"?, karena awalnya saya ikutin/pelajari data yang ada di production,
dat inputan production dari bulan maret sampai sekarang, address_province_codenya = 35

fix province code default.

---

package-lock.json
services/cases.js

Reverts jabardigitalservice/pikobar-pelaporan-backend#98

Revert "Hotfix/import cases resolve"

---

api/cases/handlers.js
api/cases/route_prerequesites.js
api/cases/routes.js
services/cases.js

Request dari kang sakti minta di UP ke production.

Regenerate id_case if district code address is changed.

---

api/cases/handlers.js
api/cases/route_prerequesites.js
api/cases/routes.js
api/cases/validations/input.js
helpers/rolecheck.js
models/Case.js
models/CaseTransfer.js
models/User.js
services/cases.js
services/cases_transfers.js

Todo: adjust to the master unit in branch development

Case transfer feature

---

helpers/rolecheck.js
services/cases_transfers.js

Excluding aborted transfer cases in the Case Transfer list.

Exclude aborted transfer cases in the Case Transfer list.

---

api/rdt/validations/input.js

add validation tool_tester for list rdt

---

models/User.js
services/users.js

1.  func save time user last login
2. add field last_login to model user

add field and function for check last login

---

api/cases/route_prerequesites.js
models/History.js
models/Unit.js
services/areas.js
services/cases.js
services/users.js

1. Adjust foreign hospital_id ref to Unit
2. Adjust old services that use Hospitall to Unit Model. (Already tested in local (getHospitals, importCases, etc) 
3. Added Exception: Cannot transfer to your own unit! (Create Transfer on Registered Cases)

Adjust hospital ref

---

helpers/casetransferhelper.js
services/cases_transfers.js

1. Added params to filter specified field in cases transfer list.

Added filter in cases transfer list.

---

services/unit.js

BUG FIXING
1. bug fix if unit_id null in existing user

bug fixing list units

---

services/users.js

Reset password ke senggol lagi kayanya

restore back reset password

---

models/User.js

1. expired token set to 8 hour work

fix expired token jwt

---

api/cases/handlers.js
services/cases_transfers.js

1. Trigger history createIfChanged method if the transfer is approved

Trigger history createIfChanged method if the transfer is approved

---

helpers/custom.js
helpers/paginate.js
server.js
services/unit.js

OVERVIEW
1. Mengurangi CODE SMELLS
2. untuk paginate label dan options bisa pakai helper/paginate

refactor unit B to A code smels

---

api/cases/route_prerequesites.js
api/cases/routes.js
helpers/casetransferhelper.js
services/cases_transfers.js

1 Added revise action exception
2. refactor allow transfer check
3. show last transfer logs based on group by unit relationship

Added revise exception & refactor allow transfer check

---

package.json
services/users.js

Overview : 
1. refactor service user :1st_place_medal:

refactor user service

---

api/cases/validations/input.js
helpers/custom.js
services/cases.js

Fix cases list sorting.

---

helpers/casetransferhelper.js

1. sort descending in case transfer log.

sort descending in case transfer log.

---

services/rdt.js

1. takeout validation when save outher auhtor location

takeout validation save input rdt

---

api/rdt/routes.js

sorry lupa, validation di pre na belum di hapus,, wkwkwkkwwk

delete validation route pre when save

---

helpers/casesheet/casesheet.js
helpers/casetransferhelper.js

1. Refactor helpers/casesheet.js (ref: 305 lines of code (exceeds 250 allowed)).
2. Refactor helpers/casetransferhelper.js (ref: Similar blocks of code found in 2 locations. Consider refactoring).

Refactor casesheet.js (305 lines of code (exceeds 250 allowed)).

---

helpers/custom.js
helpers/filter/userfilter.js
services/users.js

Overview :
1. remove duplicate function and refactor filter user list :100:

duplicate code remove and refactoring filter

---

services/rdt.js

add sorting desc at history rdt

---

services/rdt.js

1. ganti sorting nya by updateAt

change sort by update at

---

services/case_related.js
services/users.js

Overview :
1. bug fixing in lastlogin undefined
2. refactor case_related

bug fixing and refactor case_related

---

helpers/casetransferhelper.js
services/cases.js

1. Added a stage filter in cases & cases-transfer list.

Added a stage filter in cases & cases-transfer list.

---

services/rdt.js

1. add new parameter in function getExternalData

add parameter get data external API

---

api/cases/validations/input.js

1. Add a stage filter in the list of allowed query parameters in validation

Allow stage filter in param queries

---

helpers/filter/mapfilter.js
services/users.js

1. in service user method lastlogin

Development error handling

---

helpers/filter/mapfilter.js
services/map.js

1. default filter map
2. bug fixing convert

add filter default map

---

services/rdt.js

1. data error when fetch from team data
2. fix code by mode in parameter url

hot fix get data form external

---

services/users.js

bug if unit_id empty

---

helpers/filter/mapfilter.js
models/CasesRevamp.js
models/CloseContact.js
models/HistoryRevamp.js

1. add schema case revamp
2. add schema history revamp

typo in string and add schema revamp

---

api/users/handlers.js
api/users/routes.js
services/users.js

1. Added user services API getUserBySpecifiedKey (username)

Added service for get user by specified username.

---

helpers/filter/mapfilter.js
models/CasesRevamp.js
models/CloseContact.js
models/HistoryRevamp.js
models/index.js
services/case_revamp.js
services/map.js

1. create schema case revamp
2. change request filter map

revamp case and change request filter map

---

models/User.js

1 Added response in user info fields:
(+) address_subdistrict_name
(+) address_subdistrict_code
(+) address_village_name
(+) address_village_code
(+) address_street

Added complete user fields info

---

models/Case.js

1. un null response toJSON output

un-null toJSON output for list pasien

---

api/case_related/handlers.js
api/case_related/routes.js
helpers/filter/relatedfilter.js
models/Case.js
services/case_related.js

1. fix output json sesuai contoh wireframe
2. group by id kasus keterkaitan

case related fixing v.1

---

api/rdt/route_prerequesites.js
api/rdt/routes.js
services/histories.js
services/rdt.js

1. disable generate id_case ketika data_source dari external dan manual 
2. simpan ke history kasus jika input test positif, PCR, data source dari internal

Input case revision

---

helpers/custom.js
models/User.js
services/cases.js

fix conflix

---

config/manifest.js

fix dimamic port error

---

models/Case.js

1. tambah kolom nama orang tua

add parent name column in schema

---

models/Case.js
services/cases.js
services/unit.js

1. tambah kolom baru
2. handle sorting

add new column and parsing sort

---

services/cases.js

add limit result

---

models/Case.js
models/CloseContact.js

1. tambah kolom tanggal jika mengunjungi tempat publik
2. tambah kolom tanggal di list kontak erat

add date column in section close contact

---

models/CloseContact.js
models/CloseContactHistory.js
services/close_contact.js

1. Added toJSONFor method on CloseContactSchema

Added toJSONFor on CloseContactSchema

---

models/Case.js
models/CloseContact.js
models/History.js

update column cases, closecontact, and history

---

api/cases/routes.js
models/Case.js

remove unused column in response

---

models/CloseContact.js

Only validate if NIK is set. (Allow Null/Empty string)

---

api/cases_revamp/handlers.js
api/cases_revamp/routes.js
helpers/cases/revamp/handlerpost.js
services/case_revamp.js

1. membuat endpoint untuk single entry atau multiple kontak tanpa kasus

add endpoint create close contact only multiple or single

---

helpers/cases/revamp/handlerpost.js
services/case_revamp.js
services/cases.js

1. change logic generate cases

Bug fixing

---

api/cases_transfers/validations/input.js

leftover code onn previous commit

---

api/cases_transfers/validations/input.js
models/Case.js
services/case_revamp.js

update data type

---

models/CloseContact.js

remove enum gender in Close contact schema

---

models/Case.js
services/case_revamp.js

1. tambahan kolom baru tempat kerja
2. set default value to null

add new column in schema case and set default value

---

services/cases_transfers.js

corrected error callback

---

models/CloseContact.js

Remove creation attributes in Close-Contact details

---

.editorconfig

1. coba dulu yang sederhana seblum masuk ke eslint
2. pasang extension `EditorConfig for VS Code`

code styling

---

models/CloseContact.js
services/close_contact.js

populate createdBy

---

services/case_revamp.js

1. handle input single dan multiple

handle single and multiple

---

models/Case.js

Added flag 'is_patient_address_same'

---

models/History.js

1. add column n history is_patient_address_same

add column is_patient_address_same

---

services/histories.js

1. edit fungsi pembanding data object

hot fix cannot save history

---

helpers/filter/exportfilter.js
models/Case.js
models/History.js
services/cases.js

1. tambah kolom tanggal gejala di schema case
2. tambah kolom terdapat gejala di schema history

add new column

---

api/cases/validations/input.js
helpers/custom.js
services/cases.js

modify sorting

---

api/dashboard/handlers.js
api/dashboard/routes.js
helpers/sectionnumber.js
services/dashboard.js

##Dashboard summary input test 
1. relasi task #367 
2. fitur baru membuat api summary input test

Dashboard input test

---

services/case_dashboard.js

other locations included in hospital location

---

models/History.js
services/case_dashboard.js

set current_location_type to uppercase & required

---

services/case_dashboard.js

fix closecontact aggregate rules

---

models/Case.js
models/History.js
services/case_dashboard.js

set final_result as required field

---

services/cases.js

Added query sort handler

---

helpers/constant.js
helpers/filter/exportfilter.js

1. status pasien terahir baru di export

export new final result

---

api/cases/handlers.js
helpers/pdftemplate/components/epidemiological-investigation/clinical-information.js
helpers/pdftemplate/components/epidemiological-investigation/close-contact-list.js
helpers/pdftemplate/components/epidemiological-investigation/patient-identity.js

- improve new criteria & final_result

Improved PE-Form 

---

api/cases/handlers.js
helpers/pdftemplate/components/epidemiological-investigation/clinical-information.js
helpers/pdftemplate/components/epidemiological-investigation/close-contact-list.js
helpers/pdftemplate/components/epidemiological-investigation/patient-identity.js

- improve new criteria & final_result

Improved PE-Form

---

api/cases_verifications/handlers.js
api/cases_verifications/index.js
api/cases_verifications/package.json
api/cases_verifications/routes.js
api/index.js

Added API revamp/case-verifications

---

services/case_revamp.js

added case check exception (except deleted)

---

api/cases/route_prerequesites.js
api/cases_verifications/routes.js

Handle if caseId isn't found.

---

api/close_contact/routes.js

1. disabled district input scope

[close contact] disabled district input scope

---

helpers/cases/revamp/handlerpost.js
services/cases.js
services/cases_verifications.js
services/rdt.js

Add 3 digit number

---

services/cases.js

* mengurangi proses loading jadi cek array nya di limit aj ketika mau generate id_case

hotfix id-case agar tidak load semua data

---

api/cases/handlers.js
helpers/cases/revamp/handlerget.js
services/case_revamp.js

1. Added getSummary func in case revamp service.

Added case summary badge func.

---

api/category/handlers.js
api/category/routes.js
docker-compose.yml
models/History.js
models/Specimen.js
models/index.js
services/category.js

* menambah field pemeriksaan penunjang untuk input kasus pelaporan
* relasi card #409

Pemeriksaan penunjang

---

package.json

* edit runing npm nodemon for support all OS
becase now i'm use windows wkwkwkwkwkwkwkwk 🤣 🤣  soorryy

edit run script npm nodemon for all Oprating sistem

---

models/History.js

* menambahkan filed untuk form faktor riwayat perjalanan
* link card #411

add field for history factore travelling

---

api/case_related/handlers.js
api/case_related/index.js
api/case_related/routes.js
helpers/constant.js
helpers/filter/relatedfilter.js
services/case_related.js

1. membuat api endpoint untuk peta keterkaitan
2. sumber data dari `id_case_related`

map case related

---

helpers/filter/dailyreportfilter.js
helpers/reports/case.js
helpers/reports/rdt.js
services/reports.js

1. Refactor daily-report (optimized)
2. Init rdt section

Refactor & Init rdt section

---

models/Unit.js

* karena data kemarin2 ada update data rs rujukan, non rujukan dan darurat 
* relasi card #370

add some rs type and code faskes

---

helpers/filter/relatedfilter.js
services/case_related.js

1. merubah output json sesuai request frontend
2. merubah find ke aggregate query

change output json, find to aggregate query

---

helpers/custom.js
models/Case.js
services/case_related.js
services/map.js

change output by id_case

---

helpers/filter/relatedfilter.js

change number to string

---

models/History.js

bug fix field miss

---

helpers/cases/revamp/handlerget.js

Added leftover require

---

services/rdt.js

**kronologi**:  data kasus yang ada di laporan kasus selalu di anggal dari pikobar 
_catatan :_ 
setelah installl appconfig di vscode spasi nya jadi geser sendiri

bug fix rdt findinternal data

---

services/rdt.js

* tidak bisa mnyimpan data ketika nik atau no telp null atau empty string

bug fix can't save rdt

---

models/CloseContact.js

added activity on response

---

api/rdt/validations/input.js
services/rdt.js

**catatan**
ada comit revert jadi file changes nya ga ada.. cek2 di commit pertama nya

Bug fix rdt

---

services/case_related.js

change logic optimize result

---

helpers/custom.js
helpers/filter/exportfilter.js
models/Category.js
services/category.js

1. menambahkan kolom label di schema category dan refactor old code version
2. handle kolom not exists in export

refactor category and add field handling export column

---

models/Case.js

* filed faktor kontak paparan pindah ke history

delete field factor contat

---

services/rdt.js

fix rdt multiple insert

---

helpers/pdftemplate/components/epidemiological-investigation/clinical-information.js
helpers/pdftemplate/components/epidemiological-investigation/contact-tracing-advanced.js
helpers/pdftemplate/components/epidemiological-investigation/contact-tracing.js
helpers/pdftemplate/components/epidemiological-investigation/diagnosis.js
helpers/pdftemplate/components/epidemiological-investigation/patient-identity.js

Improved PE Form

---

api/occupations/handlers.js
api/occupations/index.js
api/occupations/routes.js
helpers/filter/exportfilter.js
helpers/paginate.js
models/Occupation.js
services/category.js
services/country.js
services/map.js
services/occupations.js

1. refactor beberapa master style code jadul ke style code sekarang
1. indenttation file, menghapus modul yang tidak terpakai
1. fitur inti belum di refactor

refactor old version code

---

helpers/filter/mapfilter.js

1. tambah filter di peta sebaran

add filter in map

---

models/History.js

1. added current_hospital_type into model scheme
2. inject current_hospital_type  onSave

added preSave histories

---

helpers/custom.js

change timezoe to moment

---

helpers/pdftemplate/components/epidemiological-investigation/patient-identity.js

rounding age month

---

services/case_revamp.js

_meneysuaikan filter pada list kasus_dengan mengecualikan last_history yg not exists or null_

exclude cases without lasthist

---

api/index.js
api/inject/handlers.js
api/inject/index.js
api/inject/package.json
api/inject/routes.js
services/index.js
services/inject.js

1. inject last history jika kosong

inject last history

---

api/history_travel/handlers.js
api/history_travel/index.js
api/history_travel/package.json
api/history_travel/routes.js
api/index.js
models/History.js
services/history_travel.js
services/index.js
services/inject.js

finish feature history-travell

---

api/index.js
api/public_place/handlers.js
api/public_place/index.js
api/public_place/package.json
api/public_place/routes.js
models/History.js
services/index.js
services/public_place.js

feature public place crud

---

services/rdt.js

* untuk menghandle inject DB insert input test

Multiple insert data

---

api/index.js
helpers/pdftemplate/components/epidemiological-investigation/contact-tracing.js
package-lock.json
package.json

Reverts jabardigitalservice/pikobar-pelaporan-backend#502

Revert "Bump bl from 2.2.0 to 2.2.1"

---

helpers/pdftemplate/components/epidemiological-investigation/contact-tracing-advanced.js
helpers/pdftemplate/components/epidemiological-investigation/contact-tracing.js
helpers/pdftemplate/components/epidemiological-investigation/inspection-information.js

fields:
1. close_contact_premier
2. visited_local_area
3. inspection_support

[pe-form] adjust based on revamped schema

---

helpers/reports/handler.js
helpers/reports/transformer.js

fields:
1. travelling_history_before_sick_14_days
2. inspection_support

[daily-report] adjust based on revamped schema

---

api/history_travel/handlers.js
api/history_travel/routes.js
api/local_transmission/handlers.js
api/local_transmission/routes.js
api/public_place/handlers.js
api/public_place/routes.js
services/history_travel.js
services/local_transmission.js
services/public_place.js

1. deleted id_case in param local transmission, public plcae and history travell

remove id_case in delete filter

---

api/index.js
api/inspection_support/handlers.js
api/inspection_support/index.js
api/inspection_support/package.json
api/inspection_support/routes.js
services/index.js
services/inspection_support.js

* CRUD Pemeriksaan penunjang #497

Inspection support

---

services/inspection_support.js

* ada warning katanya cara code update nya sudah deprecated

fix code update

---

services/rdt.js

* inject data untuk input test lewat google shitts

bug fix inject data input test

---

models/RdtHistory.js
services/rdt.js

Injectdata code fix

---

api/inject/handlers.js
api/inject/routes.js
services/inject.js

* api baru untuk inject data dari excel atau speredsheet

api inject data input test

---

api/index.js
api/v2/cases/handlers.js
api/v2/cases/index.js
api/v2/cases/package.json
api/v2/cases/routes.js
api/v2/cases/validations/input.js
models/Case.js
services/cases.v2.js
services/index.js

* sementara dari FE baru request API ini dulu untuk simplified di aksi ceate kasus
- jadi di ui nya ada perubahan terkait simplikasi penginputan tiap section
- jadi nanti juga ada beberapa indikator kelengkapan  di tiap section

[API/v2/cases] Simplified creating new case

---

helpers/closecontact/handler.js
services/cases_closecontact.js

1. improve rules for appending relatedcase
2. renaming to meaningful variable (hopefully wkwk)

improve rules for appending relatedcase

---

api/cases/handlers.js
api/cases/routes.js
api/v2/cases/handlers.js
api/v2/cases/routes.js
services/cases.js
services/cases.v2.js

api case section status

---

services/search.js

improve search sercvice

---

api/v2/cases/route_prerequesites.js
api/v2/cases/routes.js
helpers/cases/revamp/handlerpost.js
helpers/constant.js
models/Case.js
services/case_revamp.js
services/cases.js
services/cases.v2.js
services/cases_closecontact.js

1. kodefikasi id_case
2. list case 'is_west_java' exception
3. adjust global rules

Init case outside jabar handler

---

helpers/constant.js

corrected global rules

---

models/Case.js
models/History.js

- set clinical information to historical records

set clinical information to historical records

---

services/cases_closecontact.js

added projection subditrict & village name

---

api/histories/handlers.js
api/histories/routes.js
services/histories.js

Added API update specific history

---

models/Case.js
services/cases.v2.js

added transmission type pattern fields

---

helpers/cases/flagger.js
models/Case.js
services/cases.v2.js

Added Case flagger middleware on Case schema.

Case flagger middleware

---

helpers/filter/casefilter.js
helpers/filter/exportfilter.js
services/cases.js

export cases

---

models/History.js

unset required on status

---

helpers/filter/exportfilter.js

add column

---

api/histories/handlers.js
api/histories/routes.js
models/History.js
services/histories.js

added API delete specific history

---

helpers/cases/flagger.js
models/Case.js
services/cases_closecontact.js

1. Added flagging on event pull
2. Try to fix cognitive complexity `helpers/cases/flagger.js`
3. Try to fix similiar blocks `services/cases_closecontacts.js`

Added flagging on event pull + refactor

---

api/cases/routes.js
api/cases_closecontact/handlers.js
api/cases_closecontact/route_prerequesites.js
api/cases_closecontact/routes.js

1. _Similar blocks of code_
2. _Function exports has 72 lines of code_
_**This PR Codeclimate Progress:**_  _14 fixed issues_

refactor api handler&routes

---

api/cases/route_prerequesites.js

corrected check condition on update

---

helpers/cases/global.js
services/cases_closecontact.js

**Naming**: `helpers/cases/prerequesites.js `→` helpers/cases/global.js `
**functionality:**
- requirement func to generate id case to support multiple insertion cases
Minta tolong di review dulu kang @sandisunandar99 @firmanJS

naming as global helper

---

services/rdt.js

* tidak bisa input hasil test karena tidak ada validasi data yang sudah di delete bisa di inputkan kembali

Hot-fix insert input test

---

helpers/aggregate/demographicaggregate.js

1. wrong column in aggregate
1. count column by age
https://github.com/jabardigitalservice/pikobar-pelaporan-backend/issues/603

wrong column

---

models/History.js
services/histories.js

Added cache field of 'last_date_status_patient' on History schema

---

helpers/aggregate/demographicaggregate.js
helpers/aggregate/func/index.js
helpers/aggregate/recapaggregate.js

1. adding filter in demograpic recap
https://github.com/jabardigitalservice/pikobar-pelaporan-backend/pull/606

add filter by criteria

---

api/category/handlers.js
api/category/routes.js
helpers/request/index.js
models/Hospital.js
models/Unit.js

1. Model units, and hospital
2. Change service and route category

change rate d to a per file

---

helpers/constant.js
models/Case.js
services/cases.js
services/cases.v2.js
services/cases_verifications.js

1. new verification status called "draft"
2. added leftover an old existing field "health_workers" on case scheme

Feature/cases verification (Adjustment based on latest flow)

---

api/case_dashboard/handlers.js

miss total(export-dashboard):

---

helpers/pdfmaker.js
helpers/pdftemplate/components/epidemiological-investigation/clinical-information.js

1. Hide Header
2. Adjustment layout on `final_result`(_patient status_) from _checkbox_ to _label text_

Feature/epidemiological-investigation-form (adjustment layout)

---

api/case_dashboard/handlers.js

add column (dashboard-demographic):

---

api/case_dashboard/handlers.js

1. revisi name of file export add critertia and name
#613

revision file name export

---

api/case_dashboard/handlers.js

##OVERVIEW

---

helpers/cases/sheet/getters/history.getters.js
helpers/cases/sheet/helper.js
helpers/dictionary/id.json

1. handling error on empty records

update error handler

---

helpers/filter/relatedfilter.js

Feature/network-graph | fix "continue" iteration

---

helpers/cases/sheet/getters/case.getters.js
helpers/cases/sheet/getters/index.js
helpers/cases/sheet/helper.js
helpers/cases/sheet/reference.js
helpers/cases/sheet/validator.js

1. update validator
2. patch -> wrong converting exceldate
3. force transform age to decimal

Feature/cases-import | update validator

---

api/cases/handlers.js
services/cases.js

fix case summary

---

helpers/filter/relatedfilter.js

improve relatedFilter func

---

api/v2/cases/validations/input.js
helpers/cases/sheet/getters/case.getters.js

update birth_date validator

---

models/Case.js
services/histories.js

1. remove column close_contact_health_worker
1. add comment in schema

bug-fix(history-case):

---

models/Case.js
services/histories.js

1. issue handle column close_contact_health_worker not used in new case
1. add comment in schema

Hot fixing issue

---

services/cases.v2.js

aggregate handle null size

---

services/histories.js

1. hot fixing using .allowDiskUse(true) for handler memory limit in aggregate

Hot fix/export clinic

---

services/histories.js

ignore delete_status on POST request

---

services/histories.js

1. Cek history exists (exclude delete_status)

check  exists, exclude deleted history

---

api/case_dashboard/handlers.js
api/validations.js
helpers/aggregate/demographicaggregate.js

1. improvment dashboard demographic
1. add age greather than 80

improvment(dashboard):

---

helpers/filter/exportfilter.js

1. add column code case in case list export
task https://github.com/jabardigitalservice/pikobar-pelaporan-frontend/issues/817

hot-fix(add-new-column-export):

---

helpers/custom.js
helpers/export/cases/column.js

1. handle if column undefined or null
1. handle if coumn not exists
#676

hot-fix(export):

---

services/histories.js

1. imporove existing service: getHistoryByCase
@firmanJS @sandisunandar99

imporove existing sevice: getHistoryByCase

---

api/unit/handlers.js
api/unit/index.js
api/unit/routes.js
models/Unit.js
services/unit.js

1. Codeclimate week 3 remove unused method in unit
2. refactoring unit

example unit models

---

services/areas.js

1. bug fixing result after refactoring

bug-fix(areas-hospital):

---

api/history_travel/handlers.js
api/history_travel/routes.js
api/inspection_support/handlers.js
api/inspection_support/routes.js
api/local_transmission/handlers.js
api/local_transmission/routes.js
helpers/global/crud.js
services/inspection_support.js
services/local_transmission.js

1. change rate D, C to A
1. minor 8 next improve code quality

trying refactor local transmission

---

services/search.js

handle concat string ifnull

---

api/cases/route_prerequesites.js
api/helpers.js
api/rdt/route_prerequesites.js
services/rdt_histories.js
utils/conditional.js

1. change rdt histories logic
1. change rdt pre request rating F to A
1. change cases route F to D next improve with new branch

codeclimate-week3(task-3):

---

api/history_travel/index.js
api/history_travel/routes.js
api/inspection_support/index.js
api/inspection_support/routes.js
api/local_transmission/index.js
api/local_transmission/routes.js
services/public_place.js

1. inspection support route
1. history travel route similar block of code fix

codeclimate(rating-D):

---

helpers/pdftemplate/components/epidemiological-investigation/contact-tracing-advanced.js
helpers/pdftemplate/components/epidemiological-investigation/contact-tracing.js
helpers/pdftemplate/components/epidemiological-investigation/inspection-information.js
helpers/pdftemplate/components/epidemiological-investigation/symptoms.js
helpers/pdftemplate/helper.js

1. quick refactor section contact-tracing

refactor pe-form contacttracing

---

api/reports/handlers.js
api/reports/index.js
api/reports/routes.js
helpers/reports/handler.js
helpers/reports/transformer.js
services/reports.js

improvement(daily-report):

---

config/manifest.js

loging akses endpoint agar bisa ter record di cloud watch nya AWS

improvment manifest root

---

api/cases/handler_explode.js
api/history_travel/handlers.js
api/inspection_support/handlers.js
api/inspection_support/routes.js
api/local_transmission/handlers.js
api/public_place/handlers.js
helpers/request/index.js

Bug fix in handlker inspecction_support, local_transmission and public place

bug fix error handler

---

api/cases/routes_explode.js

1. change routes api/case/multiple-update to  api/v2/cases/multiple-update

bugfix routes

---

services/areas.js

add rs jabar query

---

services/cases_other.js

1. add condition multiple update to histories

multiple update to clinic histories

---

services/cases_other.js

##OVERVIEW
1. change conditonal multiple update for history

multiple update condtion history

---

api/index.js
api/notifications/handlers.js
api/notifications/index.js
api/notifications/package.json
api/notifications/routes.js
api/users/handlers.js
api/users/routes.js
services/cases.v2.js

1. not used notify when creating a new case (cause it's still a draft)
2. Separeted API notification

[Fix] not used notify when creating a new case (cause it's still a draft) & Separeted API notification

---

services/cases.js

1. remove last_date_status_patient in sorting
2. sort by updated

updated sorting cases

---

api/notifications/handlers.js
api/notifications/routes.js
services/notifications.js

1. Added API for getting user notif summary (read/unread)

Feature/notifications: added API user notif summary

---

api/case_related/handlers.js
helpers/aggregate/topaggregate.js
helpers/custom.js
helpers/pdftemplate/components/epidemiological-investigation/clinical-information.js
services/case_dashboard.js

Codeclimate refactoring change rate to A

codeclimate(week5):

---

helpers/notification.js

Remove uppercase on notif message

---

helpers/filter/notificationFilter.js

notification(improvement):

---

helpers/aggregate/groupaggregate.js
helpers/aggregate/rdtaggregate.js

add handle if monthly is empty array

improvement dashboard(hasil-test)

---

helpers/aggregate/groupaggregate.js
helpers/aggregate/rdtaggregate.js
helpers/constant.js

1. remove number date to date array string

change number to date

---

helpers/aggregate/groupaggregate.js
helpers/aggregate/rdtaggregate.js

1. change labeling pcr positif, negatif, invalid

change labeling pcr

---

helpers/aggregate/groupaggregate.js
helpers/aggregate/rdtage.js
services/dashboard.js

##OVERVIEW
- feedback for result en to id

dashboard hasil test

---

config/config.js

decode private key firebase for k8s

decode private key

---

helpers/aggregate/rdtage.js
helpers/aggregate/rdtgender.js

1. bug fix filter date in dashboard hasil test by gender

bug fix filter date by gender

---

services/rdt.js

mengubah bahasa labeling ketika update dari inggris ke indonsesia

change labeling in edit en to id

---

helpers/aggregate/groupaggregate.js
helpers/aggregate/rdtaggregate.js

menambahkan default tahun berjalan sekarang ketika default filter dashboard hasil tes
#800

update default date monthly grapic

---

config/config.js

change config

---

helpers/aggregate/groupaggregate.js
helpers/aggregate/rdtaggregate.js

mengubah kolom createdat to test_date

change createdAt to test date

---

api/v2/cases/validations/input.js
helpers/cases/sheet/validator.js

tambah redaksional jika status pasien terakhir tidak sesuai dengan ketentuan
#806

add redaction(import-case):

---

helpers/cases/sheet/validator.js

mengubah redaksi status pasien terakhir ke bahasa indonesia
#806

change redaction(import-case):

---

helpers/cases/sheet/validator.js

merubah redaksi ketentuan jika status pasien terakhir tidak sesuai ketika import
#806

change rule import(final_result):

---

api/cases/handlers.js
api/cases/routes.js
api/cases_transfers/handlers.js
api/search/handlers.js
services/cases.js

refactoring (week-5):

---

helpers/filter/exportfilter.js
helpers/filter/historyfilter.js

batch limit on export

---

services/cases.js

mengatasi error saat sorting di aggregate
https://docs.mongodb.com/manual/reference/method/db.collection.aggregate/#example-aggregate-method-external-sort

allowdiskusage

---

helpers/filter/historyfilter.js

ubah urutan riwayat pasien sesuai list tabel

change filter histories

---

api/histories/handlers.js
helpers/filter/historyfilter.js
services/public_place.js

Bug fix/public place

---

helpers/filter/exportfilter.js
helpers/filter/historyfilter.js
utils/index.js
utils/sort.js

hot fix sort berdasarkan request frontend

Hot Fix Export Sorting By Request

---

helpers/cases/sheet/validator.js

Hot fix check redaction in import

Hot fix/import cases

---

api/unit/handlers.js
helpers/filter/unitfilter.js
services/unit.js

bug fix list unit berdasarkan author

bug fixing list unit

---

package.json

- add package redis in npm module

minor package.json

---

utils/sort.js

- pre release production also fixing conflict merge code flter export in bug fixing
- this branch has merged to development

Bug fix/filter export

---

.gitignore
package.json
utils/sort.js

Rilis beberapa branch yang belum up ke production
_**catatan**_ 
jangan dulu merge :smile:

Pre release production

---

Makefile
helpers/integration/index.js

- make action when publisher edit event

make action when publisher edit event

---

services/areas.js

finish setup redis untuk list hospital

caching list hospital

---

services/country.js

missing key redis

---

services/areas.js

caching untuk list district city

caching district city

---

services/areas.js

maping data district city

---

api/country/handlers.js
api/country/routes.js
services/areas.js

add endpoint for clear all cache key redis

redis flush aall

---

helpers/aggregate/rdtage.js
models/Rdt.js

bug fix aggregate summary hasil test and data type string to number

change type data and convert

---

helpers/integration/index.js
integration/index.js

- fix error pubsub when subscribed by filter phone number without nik

add filter and eror msg Pubsub

---

services/unit.js

hot fix unit

---

helpers/email/index.js
services/queue.js

change secure connection for ses aws email

secure connection email

---

helpers/integration/index.js

1. bug fixing when search cases filter deleted and verified

bug fix filter user

---

helpers/integration/index.js

- wrong field filter get cases :smile:

wrong field filter

---

Dockerfile.dev
Dockerfile.release
package.json

remove nodemon for prod

---

Dockerfile.dev
Dockerfile.release
package-lock.json
package.json

- fixing entrypoint docker and package.json

fix package and entrypoint docker prod and stagging

---

services/queue.js

minor tambah select `job_name` di list queu

bug fix minor add column job_name

---

services/map.js

implement caching in map service

caching feature(map):

---

services/case_related.js

update set key redis by username

update set key map

---

api/country/handlers.js
api/country/routes.js

tambah endpoint untuk reset key redis

add endpoint reset key redis

---

helpers/constant.js
models/User.js

mengganti redaksi ketika duplikat email
#842

change redaction(users):

---

services/areas.js

mengganti format expiretime redis versi 6.x tidak support perhitungan milisecond

milisecond not support in redis 6.x

---

captain-definition

[devops] add template file caprover

---

services/case_dashboard.js

add date version in response

---

helpers/filter/casefilter.js

kurang parameter kriteria di query strings

missing criteria filter

---

helpers/integration/index.js

add alternatif filter

---

helpers/integration/index.js

rollback source filter

---

api/cases/route_prerequesites.js
api/helpers.js
api/rdt/handlers.js
api/rdt/routes.js
helpers/custom.js
helpers/filter/casefilter.js
helpers/filter/notificationFilter.js
helpers/paginate.js
services/case_related.js
services/cases.js
services/rdt.js
services/users.js

Mengurangi code smells and duplicate code dari F,D,C,B ke A per file

maintainability pelaporan(codeclimate):

---

api/cases/routes.js
helpers/pdftemplate/components/epidemiological-investigation/treatment.js
helpers/rdt/custom.js
services/inject.js
services/rdt.js

Menurunkan code smels dan duplikasi code di pelaporan

refactoring (day2):

---

helpers/export/histories/column.js
helpers/filter/log.js
helpers/job/export_xlsx.js
services/queue.js

- bug fix redaction name file xlsx
- bug fix filter by status
#952

bug fixing redaction export xlsx

---

jest.config.json
services/queue.js
utils/pagination.js

change estimatedDocumentCount, to countDocuments

change checkout

---

services/queue.js

minor change method count monggo

minor change condition type

---

utils/pagination.js

minor change size pagination

---

services/queue.js

change query mongo find and lean

update query list

---

api/index.js
config/config.js
config/manifest.js
server.js

- remove capture exceptions in is.Boom
- using middleware sentry, request and error

update config sentry

---

config/manifest.js

if null change local config

---

api/index.js
server.js

- modification sentry just get error status code 404 and 500

get error just 404 and 500

---

helpers/job/export_xlsx.js
helpers/job/index.js
services/queue.js

minor change position update email and create job queue

minor change position validation

---

Jenkinsfile.jacloud

- Bug fixing file typo in config k8s

Bugfix - Typo in file config 

---

integration/index.js

- open module integration labkes

open module integration labkes

---

services/cases.js

- bug fixing list case not show becase _id not identifier

bug fix list case now shown because _id not identifier

---

api/index.js

change capture sentry 404 is takedown,

change capture sentry

---

helpers/integration/splitpayloadlabkes.js
services/integration.js

- change is other location flaging

chnge is other location

---

services/queue.js

update position validation

---

helpers/dictionary/id.json

- change name label notification

chnage name message label

---

api/cases/route_prerequesites.js
services/cases_other.js

updated method services

---

api/areas/handlers.js
services/areas.js

hot-fix issue list area

---

services/areas.js

minor users params

---

helpers/integration/index.js
services/integration.js

- disable integration data, by district city

disabled find user by district and subdistrict

---

api/cases_closecontact/route_prerequesites.js

minor change handler pre request undefined

minor change undefined function call

---

helpers/email/index.js
helpers/export/index.js
helpers/job/export_xlsx.js
helpers/job/index.js
helpers/queue/index.js
services/queue.js

bug fix queue email, and log info sent email

Hot fix/queue email

---

api/helpers.js

handler error in core hapi reply interface called twice ref : https://stackoverflow.com/questions/41993642/hapijs-reply-being-called-twice

Bug fix/core hapi call twice

---

.github/workflows/release-production.yml
.github/workflows/release-staging.yml

Add github action sentry release workflow for adding version info on deployment.
https://docs.sentry.io/product/releases/
https://github.com/marketplace/actions/sentry-release
Gasss gasss.

Add github action sentry release workflow

---

services/reports.js

add disclaimer caching for menu daily report
#1067

add info date version cache data

---

services/case_related.js
services/map.js

add info date version of data map
#1068 #1069

updated caching for map

---

api/helpers.js

##OVERVIEW
handler error in core hapi reply interface called twice ref : https://stackoverflow.com/questions/41993642/hapijs-reply-being-called-twice

handler core hapi

---

helpers/job/index.js
helpers/queue/index.js
services/dashboard.js

updated redis key

---

helpers/job/index.js

sorry remove console log minor guys :rofl:

remove console

---

api/helpers.js

bug fix for eeror reply in sentry https://sentry.io/organizations/jabardigitalservice/issues/2501074341/?project=5745425&query=is%3Aunresolved

updated call twice in reply helpers

---

services/map.js

wrong set time

---

services/dashboard.js

remove parsing

---

services/reports.js

updated caching time

---

services/queue.js

change time

---

helpers/email/index.js

updated link button email

---

api/cases_closecontact/route_prerequesites.js

rename service undefined called

bug fix undefined cases

---

config/config.js
helpers/job/index.js
helpers/queue/index.js

setup job redis

---

helpers/constant.js
helpers/email/index.js

styling email

---

services/queue.js

Up @khihadysucahyo @sandisunandar99

Minor wrong create queue
